  GNU nano 8.1                                                         docker-compose.yml                                                                   version: '3'
services:
  db:
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=odoo16
      - POSTGRES_PASSWORD=abcd*1234
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo16:
    image: odoo:16
    user: root
    depends_on:
      - db
    ports:
      - "8016:8069"
      - "8072:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo16
      - PASSWORD=abcd*1234
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      #- ./entrypoint.sh:/entrypoint.sh
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
